name = "LengthChannels"
uuid = "6e84ca90-c4c0-49b1-bdb7-24cdbeba32de"
authors = ["Fredrik Bagge Carlson <baggepinnen@gmail.com>"]
version = "0.1.1"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
